### ISSUE TITLE
For avatarUrl

### ISSUE THREAD

**Issue by lolimay1999** [ahucv/Homepage#1]
You can drag your avatar image (drag jpg or png) file here to get the avatar URL.

**Comment by lolimay** [comment]
![深度录屏_选择区域_20190801234501](https://user-images.githubusercontent.com/32427260/62308058-57689f80-b4b7-11e9-8c57-c13ac63b522a.gif)

**Comment by liwenjielongren** [comment]
https://user-images.githubusercontent.com/52265815/62407008-1f12af80-b5e4-11e9-9168-978427a0e296.jpg

**Comment by bigmoking** [comment]
![Cache_ab269b2f62a81cb](https://user-images.githubusercontent.com/48269129/62407926-e3cbad00-b5f2-11e9-906f-759304678093.jpg)

**Comment by Yuhe233333** [comment]
![IMG_20190803_122504](https://user-images.githubusercontent.com/31096967/62408406-3d37da00-b5fb-11e9-88c7-acef1934f248.jpg)

**Comment by HuoXuan1314** [comment]
![IMG_20190614_142846(1)](https://user-images.githubusercontent.com/53636752/62408450-c818d480-b5fb-11e9-9c12-51d40b872ad1.jpg)

**Comment by SaintLogos1234** [comment]
https://user-images.githubusercontent.com/19261529/62409880-6b73e480-b610-11e9-9101-5abe1c7cd2b5.jpg

**Comment by SaintLogos1234** [comment]
https://user-images.githubusercontent.com/19261529/62410110-cd821900-b613-11e9-86ff-3658bb9bf17a.jpg

**Comment by SaintLogos1234** [comment]
https://user-images.githubusercontent.com/19261529/62410135-48e3ca80-b614-11e9-890a-98c273d60b37.jpg

**Comment by wenmeixu** [comment]
https://user-images.githubusercontent.com/53634030/62418646-06b49a80-b6a1-11e9-8fda-fa4566a81b89.jpg

**Comment by wyl6587** [comment]
https://user-images.githubusercontent.com/45382635/62595687-e93a3780-b911-11e9-81b6-e917138306ea.jpg
